package.json, src/context/webview.ts, src/variables.ts
=> release v0.0.2

.github/workflows/update-release-version.yml, package.json, src/commands/preview.ts, yarn.lock
=> release v0.0.5

src/schemas/book.ts, src/webviews/src/components/BookPreview/BookPreview.module.scss, src/webviews/src/components/BookPreview/index.tsx
=> feat: 本のプレビューで除外されているチャプターを分かりやすく表示するように修正した

src/schemas/article.ts, src/schemas/book.ts, src/schemas/bookChapter.ts
=> fix: FrontMatterでslugが上書きされないように修正

package.json
=> fix: activationEventsを`*`に修正

src/schemas/bookChapter.ts
=> fix: 数字付きのチャプターのslugに数字が含まれてしまうバグを修正

README.md, package.json, snippets/snippets.json
#40 
よろしくお願いします
デフォルトではmarkdownのスニペットは無効になっているため、READMEに有効にする方法を記載しました。
もしも、分かりづらい内容がある場合は訂正をお願いします！
=> スニペットを追加する

README.md, package.json, snippets/snippets.json, src/schemas/article.ts, src/schemas/book.ts, src/schemas/bookChapter.ts, src/webviews/src/components/BookPreview/BookPreview.module.scss, src/webviews/src/components/BookPreview/index.tsx
**changes**
- #35 
- #36 
- #37 
- #38 
- #41
=> release v0.0.6

.github/workflows/release.yml, package.json
=> release v0.0.8

package.json, src/commands/preview.ts
- コマンドパレットから実行しやすいように package.json 内の command のタイトルを修正しました
- preview コマンドが実行できない場合にエラーメッセージを表示するように修正しました
Resolves #54 
=> fix: コマンドパレットから実行しやすいようにコマンドのタイトルを修正

package.json, src/commands/newBook.ts, src/commands/newChapter.ts, src/commands/preview.ts, src/context/commands.ts, src/utils/helpers.ts, src/variables.ts, src/webviews/src/components/BookPreview/BookPreview.module.scss, yarn.lock
**changes**
- #50
- #51
- #53
- #57
=> release v0.0.9

package.json, package.nls.ja.json, package.nls.json
`package.json` に登録されたコマンド名を置換可能文字列として登録し、英語と日本語でのコマンド定義ファイルを用意することで英語コマンドによるコマンドパレットからの検索性能と日本語コマンドによる UI やコマンドの意味合いの分かりやすさを両立させました。
Resolves #62 
=> feat: 英語による検索性と日本語による分かりやすさの両立のためにコマンドをローカライズ化

package.json, src/webviews/src/components/ArticlePreview/index.tsx, src/webviews/src/components/BookChapterPreview/index.tsx, src/webviews/src/components/BookPreview/index.tsx, src/webviews/src/components/ValidationErrors/index.tsx, webpack.config.js, yarn.lock
zenn-content-css とその他 zenn のライブラリをアップデートしました。
Resolves #58
=> feat: zenn-content-css とその他関連ライブラリのアップデート

package.json
=> chore: package.json に homepage フィールドを追加

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Pull Request テンプレートの見出しレベルを調整

README.md
- ドキュメントに記載通りに VSCode のオプションを設定するとエラーが発生しました。
- VSCode May 2022 (version 1.68) から、 `{ "editor.quickSuggestions": true }` という一括指定ができなくなったようです。 https://github.com/microsoft/vscode/pull/148773
- この PR ではスキーマ変更後のオプション指定方法に変更します。
- 変更後のオプションでエラーが発生しないことを確認しました。
Resolves #<issue-url>
- ~~実行して正しく動作しているか確認する~~
- ~~不要なコードが含まれていないか( コメントやログの消し忘れに注意 )~~
- ~~XSS になるようなコードが含まれていないか~~
=> docs: VSCode の `editor.quickSuggestions` スキーマ変更を反映

.github/workflows/update-release-version.yml
yarn から pnpm への移行で GitHub Actions が正しく動作しなかったので修正
=> fix: pnpm version コマンドのオプションが間違っていたので修正

src/commands/revealActiveFile.ts
=> refactor: 無駄なasyncキーワードの削除

src/extension.ts
プルリクエストに含む内容の簡潔な記述
Resolves #110 
=> fix: ワークスペースを開いていない場合のエラー通知削除

.vscode/settings.json, examples/example_user1/articles/sample-article.md, package.json, pnpm-lock.yaml, src/context/app.ts, src/webviews/src/components/ArticlePreview/index.tsx
https://github.com/zenn-dev/zenn-vscode-extension/pull/121
=> release v0.3.0

package.json, src/treeview/previewTreeItem.ts
=> release 0.4.0

package.json, src/treeview/previewTreeItem.ts
Reverts zenn-dev/zenn-vscode-extension#123
=> Revert "記事のソートをタイトル順にする"

package.json, src/treeview/previewTreeItem.ts
=> 記事のソートをタイトル順にする リトライ！
